// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAPIProject.data;

namespace MyAPIProject.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("MyAPIProject.data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tunisia",
                            ShortName = "TN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Russia",
                            ShortName = "RU"
                        },
                        new
                        {
                            Id = 3,
                            Name = "USA",
                            ShortName = "US"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ukraine",
                            ShortName = "UA"
                        });
                });

            modelBuilder.Entity("MyAPIProject.data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adress")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Adress1",
                            CountryId = 1,
                            Name = "Hotel1",
                            Rating = "5"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Adress2",
                            CountryId = 2,
                            Name = "Hotel2",
                            Rating = "4"
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Adress3",
                            CountryId = 3,
                            Name = "Hotel3",
                            Rating = "3"
                        },
                        new
                        {
                            Id = 4,
                            Adress = "Adress4",
                            CountryId = 4,
                            Name = "Hotel4",
                            Rating = "2"
                        });
                });

            modelBuilder.Entity("MyAPIProject.data.Hotel", b =>
                {
                    b.HasOne("MyAPIProject.data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MyAPIProject.data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
